### ISSUE TITLE
Malware on redux framework

### ISSUE THREAD

**Issue by cinghie** [No3x/wp-mail-logging#38]
Hi,

our hosting provider has reported the presence of malware to the following path:

wp-content/plugins/wp-mail-logging/inc/redux/redux-framework/ReduxCore/inc/fields/editor/field_editor.min.js

SecuriteInfo.com.Trojan.Script.655510.8251.9711.30398.UNOFFICIAL FOUND

Do you think is a false warning o there some problem on redux framework?

Regards

**Comment by No3x** [comment]
Hi @cinghie,
The source of the minified version of the file your hosting provider blames is: [field_editor.min.js](https://github.com/No3x/wp-mail-logging/blob/release/1.5.2/inc/redux/redux-framework/ReduxCore/inc/fields/editor/field_editor.min.js) (and also the not minified version does the same [field_editor.js](https://github.com/No3x/wp-mail-logging/blob/release/1.5.2/inc/redux/redux-framework/ReduxCore/inc/fields/editor/field_editor.js)) This looks really not dangerous to me.

I can't tell you what and if there is any other code in your field_editor.min.js without checking integrity with an hash (md5, sha or something else).

**Comment by iloveexploerer** [comment]
hello i also found a torjan in reduxCore>inc>Fields.editor>field_editor.min.js when i scanned a nulled wordpress theme using virus total here is the link to virus total result page 
https://www.virustotal.com/#/file/8737ed007cf4ae658b90642504aab00dab935124e9d610b8f6112086153a2986/detection
SHA256 hash of infected file is SHA256          8737ED007CF4AE658B90642504AAB00DAB935124E9D610B8F6112086153A2986
MD5             706EC4008252642E6DAAEFF8DD804CC3
SHA1            2363BF367CBAAC5A78F04A392227BF5702C654B3

**Comment by No3x** [comment]
@iloveexploerer 
Did you compare the hashes with the origin file in this 
repository? Are they equal? Is it likely for a nulled WordPress theme 
that it includes suspicious code? What has my plugin to do with it?

Because you don't provide steps to reproduce I spent time investigating:
A quick check with 
https://www.virustotal.com/#/url/e0be33aba5140089403f11217a2d0bb7dbd598711c45e7a9a129ca8d66320012/detection 
shows no detections.
Result: the checksums (e.g. sha256)
```
origin release/1.8.3:
ed26e11e29d27a0866dfb94cca4e66823b7e6302777f4373ab5efe70689d2349
yours:
8737ed007cf4ae658b90642504aab00dab935124e9d610b8f6112086153a2986
```
are different. This means the file is modified or an other version.
