### ISSUE TITLE
Illegal String Offset Errors

### ISSUE THREAD

**Issue by ThisGals** [No3x/wp-mail-logging#43]
Started receiving the following errors on a website recently (may have happened with the latest WP update; client doesn't check site often):

Warning: Illegal string offset 'to' in /.../wp-content/plugins/wp-mail-logging/WPML_Plugin.php on line 182
Warning: Illegal string offset 'subject' in /.../wp-content/plugins/wp-mail-logging/WPML_Plugin.php on line 183
Warning: Illegal string offset 'headers' in /.../wp-content/plugins/wp-mail-logging/WPML_Plugin.php on line 185
Warning: Illegal string offset 'attachments' in /.../wp-content/plugins/wp-mail-logging/WPML_Plugin.php on line 186

**Comment by No3x** [comment]
Hi @ThisGals 
this means someone calls wp_mail unusual. Do you use a external mail service like mailchimp (previous mandrill), phpmailer?

**Comment by ThisGals** [comment]
The client is using the WP Mail Bank plugin to send via SMTP using their mail account on the same server. We're now investigating whether or not it may be a change in this plugin since it recently had a major update, or a change in the server mail setup.  Thanks so much for the reply!

**Comment by No3x** [comment]
I have looked into their code. They completely overwrite the wp_mail method. Instead of returning their result object they should return the original content of the mail. They do this because they want to check if the mail was sent successfully in the test mail configuration settings.
They break the wp_mail filter.

They should [add apply_filter](https://plugins.trac.wordpress.org/browser/wp-mail-bank/tags/2.0.6/includes/mailer.php#L338) like this:
```php
$email_configuration_settings = unserialize($email_configuration_data_array);
$obj_send_test_mail = new mail_bank_auth_host($email_configuration_settings);
apply_filters( 'wp_mail', $to, $subject, $message, $headers, $attachments );
$result = $obj_send_test_mail->send_test_mail_bank($to,$subject,$message,$headers,$attachments,$email_configuration_settings); 
return $result;
```
I did not test this and I'm not sure your wp_mail is overwritten (depending on your config).
