### ISSUE TITLE
PSR-style file locations

### ISSUE THREAD

**Issue by szepeviktor** [No3x/wp-mail-logging#62]
Hello @No3x !

Would it be possible to change `class WPML_Email_Dispatcher` to `class Email_Dispatcher`
and put class files in `/inc` under `WPML`?

Maybe you have a good reason why not.

**Comment by No3x** [comment]
Hi @szepeviktor, 
I use `inc` for 3rd party lib integration/configuration.
`lib` is for 3rd party libs.
Maybe the whole code should be moved to an `src` directory.
I just did not put in in inc because it doesn't meet the meaning for what I use this directory.
If you want to apply/propose an PSR-style feel free to do so. I'm not that much familiar with php dev in difference to other dev stacks.
Why do you want to move this file? Any specific use case?

**Comment by szepeviktor** [comment]
> Why do you want to move this file? Any specific issue with it?

Where there is a class autoloader, PHP files are organized.

**Comment by No3x** [comment]
So you just don't feel comfortable with the file structure? Feel free to change anything :)

**Comment by szepeviktor** [comment]
OK!
