### ISSUE TITLE
Plugin removed from wp.org repo?

### ISSUE THREAD

**Issue by vinnyusestrict** [No3x/wp-mail-logging#67]
This is a great plugin. Why can't I find it in the wp.org repo anymore?

**Comment by No3x** [comment]
Hi @vinnyusestrict,
the plugin had to be temporarily withdrawn from the WordPress.org Plugin Directory due to an exploit.
This is already fixed in b650cda0e264925de8081dc5b2a5dace5f071c1d and in the according svn repository on WordPress.org. It has to be reviewed by the WordPress.org Plugin Directory team now.

My suggestion is to wait for this action and not to install <1.8.2 somehow.
I'm sorry for the inconveniences.

**Comment by No3x** [comment]
The plugin is available again now.
