### ISSUE TITLE
Cache result of `isInstalled`

### ISSUE THREAD

**Issue by mqudsi** [No3x/wp-mail-logging#71]
wp-mail-logging is issuing 

```sql
SHOW TABLES LIKE 'BLA_wpml_emails"
```

multiple times on each page load. The result of `No3x\WPML\WPML_InstallIndicator->isInstalled()` should be cached (or a transient if cache is not available so that it is at least not executed more than once).

The cache can be invalidated on the plugin deactivate hook.

Actually, is there a reason this is done on every page load in the first place? Why can't `upgrade()` be called with the appropriate hook in the first place?

**Comment by No3x** [comment]
I had a lot of issues with such an option. One use case that seemed to be critical was 
> As it is redundant and error prone for disabling plugin, updating files and enabling plugin again.

Please see the changes of https://github.com/No3x/wp-mail-logging/commit/ca0e71bac025ce135bec3b203ddb97a376aed9f7#diff-deb94457c1d0db1a19f6cf0c952bebf3

I need to check for an upgrade on each page because at any time the wp_mail hook can be fired. 

Suppose the following failing case: the hook fires but the db schema is still at version 1 and code is at version 2. (This is the case if the schema upgrade did not take place) 
If the schema between version 1 and 2 changed there will occur SQL errors because the plugin tries to log a mail with a different structure.

> Why can't upgrade() be called with the appropriate hook in the first place?
Can you elaborate on this? I don't understand this strategy yet. Do you have an idea?

**Comment by No3x** [comment]
Unfoutunately you did not read my response mindfully. The link also shows this pattern which was implemented previously but led to errors described above.

**Comment by mqudsi** [comment]
My point is that it isn't necessary to touch the database at all until you have need to log. So you would couple the basic check detailed above with an explicit check in the event that you need to actually read or write to the database. There definitely shouldn't be a need for any db io regardless of whether or not wp_mail()` *may* be called on this page load, only once it *is* actually called.

An alternative approach is to make your queries resilient to DB changes. If you check the db version only once you actually are ready to write to the db, you can start a mysql transaction then insert and commit only if the version hasn't changed. Another is to insert conditionally and use the number of rows modified return value to determine if the insert succeed, for example

```sql 
insert into xxx(a, b, c, d) 
select ("a", "b", "c") 
where select db_version from wpml_options = SCHEMA_VERSION
```

which would let you assert that the version hasn't changed while inserting, and if it does, the insert will return zero rows modified which you can take as a signal to update the schema and retry.

**Comment by No3x** [comment]
But there is also the view that depends on indirectly on the database schema. If one of the is different this can cause nasty bugs. Bugs that are really hard to reproduce.

My ORM doesn't support such low-level queries. And I think it would make it unneccessary complex.

## Transient
I think a transient is a good tradeoff. The mechanism must be independent of the update method. It must not rely on install/activation/deactivation hook.
A) via WordPress install or update
B) drop an update in the plugin dir and replace the files

B => The name of the transient must contain the version of the plugin. Otherwise if there is a `WPML_db_version` transient only (without version) it would say it's already installed even if the code version is higher.

I would check for the transierent WPML_1.8.5_db_version 
is set: assume schema is installed
not set: install and set

On `deactivation_hook` remove the transient only if "delete on deactivation" is enabled in the preferences.
On `uninstall_hook` unconditionally delete the transient

**Comment by mqudsi** [comment]
Transients are just like options, they can have a name and a value. So normally your transient would be called something like `wpml_db_version` and it would have a value. If the transient doesn't exist at all, the plugin isn't installed. If it exists but has a value older than `SCHEMA_VERSION`, then an upgrade is needed. There's no need to rely on the name to include the version.

But all this is secondary to my main question: why is DB logic invoked on page load? Why isn't all this done only when an email is being sent?

**Comment by mqudsi** [comment]
I don't know if you're still interested in addressing this, but this simple fix costs nothing and prevents _at the very least_ running `SHOW TABLES ...` multiple times *in one page load*:

```php
    public function isInstalled() {
        $installed = false;

        // We don't use the cached value, only its presence.
        // This is because we never cache not installed state.
        wp_cache_get('installed', 'wpml', false, $installed);
        if (!$installed) {
            global $wpdb;

            $mails = $this->getTablename('mails');
            $query = $wpdb->query("SHOW TABLES LIKE \"$mails\"");
            $installed = (bool) $query;

            if ($installed) {
                wp_cache_set('installed', true, 'wpml', 3600);
            }
        }
        return $installed;
    }
```

As an added bonus, users with caching installed get to avoid that db hit for an hour. (Ideally the uninstall code should remove the cached value, but I'm not planning on uninstalling wpml.)

**Comment by No3x** [comment]
Sure! Just so a pull request and I will test it.
